### ISSUE TITLE
有用户报错3.0版本数据库配置存在问题，create函数传参不正确

### ISSUE THREAD

**Issue by wutongshufqw** [hsyhhssyy/amiyabot-hsyhhssyy-chatgpt#11]

**Comment by hsyhhssyy** [comment]
有截图吗？具体是什么报错？
用的是mysql还是sqlite？

因为我这个程序动态创建了一个数据库，所以如果数据库引擎那边有权限限制之类的，可能会报错吧。

**Comment by hsyhhssyy** [comment]
或者实在找不到问题，就让他去amiya_plugin数据库下面做一张这个表
![image](https://user-images.githubusercontent.com/5977110/233403581-09d38277-87de-4fe2-b676-fe02f08f4c4c.png)

**Comment by wutongshufqw** [comment]
![3dbbcb1f1fa6433b](https://user-images.githubusercontent.com/87960738/233408440-97376d3b-4342-472c-aa39-e50b9e5d1b71.png)

**Comment by hsyhhssyy** [comment]
已修复，3.0.1已上架，请确认是否还有问题。

**Comment by wutongshufqw** [comment]
![7EF)CK15NBDV(B2SP R5T3_tmb](https://user-images.githubusercontent.com/87960738/233598568-bf2fb88d-a272-47ed-922e-b2ab0574ea0c.PNG)
新的报错

**Comment by hsyhhssyy** [comment]
![image](https://user-images.githubusercontent.com/5977110/233646213-d1ba5274-4cbb-4c1e-af6f-bab01764d46d.png)

看起来这是CQ的问题，我没法测试。

**Comment by hsyhhssyy** [comment]
哦我知道了，这是私聊是吧，麻烦你确认一下，这是不是私聊触发的？
做角色扮演模式的时候，我没想到会有人私聊触发ChatGPT的角色扮演
我改一下，让私聊的时候回归传统模式。

**Comment by hsyhhssyy** [comment]
![image](https://user-images.githubusercontent.com/5977110/233647111-b2ddbd74-0e20-4e33-9e15-fd86fe6290d1.png)

我加了一个限制，现在私聊不让走角色扮演了，你看一下是不是这个问题。

**Comment by hsyhhssyy** [comment]
3.0.3修复了私聊无法进行的bug，你可以看一下解决没有。

**Comment by wutongshufqw** [comment]
好惹
