### ISSUE TITLE
从3.0的版本开始在其他插件输入需要数字时无反应，退回2.6版本则可以

### ISSUE THREAD

**Issue by Cheng2k9** [hsyhhssyy/amiyabot-hsyhhssyy-chatgpt#12]
![image](https://user-images.githubusercontent.com/117975646/233793126-e7b48aac-ca88-47af-8599-c713f641879b.png)
![image](https://user-images.githubusercontent.com/117975646/233793175-e5d5f8f3-4392-4f8b-b11a-adc6482fc9dd.png)
其中log上没有任何报错信息，换成查询立绘时输入数字同样没反应，同时开关覆盖其他插件的选项照样无果
![image](https://user-images.githubusercontent.com/117975646/233793338-36199309-7fc1-475f-ac9c-e17ce57a9fbb.png)
![image](https://user-images.githubusercontent.com/117975646/233793226-5c312f94-5e58-449d-9644-87439aa68088.png)

**Comment by hsyhhssyy** [comment]
我新发布了3.0.4版本暂时解决这个问题。
但是这个问题涉及到一个兔兔的功能缺陷，可能需要我花大力气去绕开，或者让兔妈为插件增加新功能。

**Comment by Cheng2k9** [comment]
麻烦了大佬
