### ISSUE TITLE
配置GPT时遇到的问题

### ISSUE THREAD

**Issue by MATBBB0** [hsyhhssyy/amiyabot-hsyhhssyy-chatgpt#15]
您好，请问我已经把GPT插件成功安装并且设置了apikey，但是询问时发现终端会产生报错AttributeError: 'NoneType' object has no attribute 'keys'，这种情况应该怎么解决，是我http代理没配置对吗

**Comment by MATBBB0** [comment]
![QQ图片20231115184317](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/assets/121423358/f9e84559-5cdc-4478-94f8-55a2b1e06fb3)

**Comment by hsyhhssyy** [comment]
这应该是我配置项初始化的时候的一个bug
你把这个配置项切换一下然后保存，然后再切换回去，再保存，应该就好了。

![image](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/assets/5977110/048ad666-c09d-43d5-9200-e72cd7f427d5)

下个版本我会修一下。

**Comment by MATBBB0** [comment]
经典模式的这几个选项我好像都配不了，兔兔思考中的按钮我是打不开的

**Comment by hsyhhssyy** [comment]
[global_config_default.json](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/files/13365017/global_config_default.json)

那这样，你用这个文件，替换插件目录下的accessories目录下的同名文件，然后重启兔兔以后，去console里的插件配置里，点一下全局配置里的重置为默认。

**Comment by MATBBB0** [comment]
是兔兔思考中按钮点一下他不会有反应

**Comment by MATBBB0** [comment]
我先试一下替换

**Comment by MATBBB0** [comment]
我试了一下您说的替换貌似不行，然后我重新安装了3.1.0的插件版本，出现了下面这个报错
![微信图片_20231115214542](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/assets/121423358/808fa751-c826-4a42-ae6f-4881a22a15ab)

**Comment by hsyhhssyy** [comment]
不知道您是否能打开数据库，如果能打开数据库就好办了

**Comment by hsyhhssyy** [comment]
问题其实是配置项缺一个对象导致的。
旧版插件因为和新版兔兔不兼容，装上去是没用的，而且，这个bug旧版也有，看起来已经持续很久了。

**Comment by hsyhhssyy** [comment]
注意不是覆盖替换以后就好，是你需要去重置一下配置项。
相当于让console用替换后的文件作为初始配置项，给你重新初始化一下配置项。
兔兔启动的时候，如果你数据库里没有默认配置项，会给你写一个默认配置项，但是这个版本的默认配置项是错的。所以我给你一个旧的配置项，你用他替换以后，要去重置配置。
所以你记得要去按重置。
![image](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/assets/5977110/ed546256-999c-4910-80ec-9ddca95eda0b)

**Comment by hsyhhssyy** [comment]
我刚刚紧急上架了一个3.4.7，亲测可以通过重置配置项解决这个问题。和你替换文件效果一样。

**Comment by MATBBB0** [comment]
OK，我刚下计网实验课，洗个澡然后我试试看，谢谢大佬

**Comment by MATBBB0** [comment]
现在不会报错了。不过比如我问他“兔兔为什么地球是圆的”，他会回复阿米娅思考中，然后回复很抱歉博士，但是我现在暂时无法回答您的问题。我的APIKEY配置应该是对的，是不是我没有配置http代理的问题。还是说我运行兔兔的机器需要开着VPN

**Comment by MATBBB0** [comment]
是可以访问GPT的，我用CLASH开的加速器

**Comment by MATBBB0** [comment]
![QQ截图20231115234238](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/assets/121423358/95148d03-4530-4832-a699-38af0e68f38d)
![QQ截图20231115234254](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/assets/121423358/df70d2ab-4130-4aa2-9306-39cabfbaa45d)
![QQ截图20231115234329](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/assets/121423358/8f7de835-0b92-49ce-a44c-237a46646732)
现在配置像上面图里的一样，电脑是可以访问GPT，但是在Q群里询问的话貌似还是会有网络的问题连接不上

**Comment by hsyhhssyy** [comment]
那你CLASH可能需要开全局代理，我没用过CLASH，是socks模式吗？还是http？改的系统配置？改的系统代理的话，你得把系统代理也填到插件里。

**Comment by MATBBB0** [comment]
好像是用系统代理，系统代理要咋填到插件里

**Comment by MATBBB0** [comment]
现在在clash配置了全局代理不过好像还是不行，是不是插件配置我还有问题

**Comment by hsyhhssyy** [comment]
你先看一下ChatGPT的报错，或者你看一下你openai lib的版本
openai的lib最近更新了1.0.0，和现有代码不兼容，你需要降版本。
我下一个版本会更新兼容。

**Comment by MATBBB0** [comment]
我自己开ChatGPT用的话倒没有报错，openai版本我昨天降到了0.28.0

**Comment by hsyhhssyy** [comment]
网页和Api并不是同一个东西，你Clash开了全局代理，很可能只是修改了系统的代理配置，但是你不去插件里配，插件不会用这个代理的。
你需要理解一些科学上网的基础知识。

**Comment by hsyhhssyy** [comment]
要不你还是等下个版本用文心一言吧

**Comment by hsyhhssyy** [comment]
ChatGPT如果不能用，他报告什么错误？
或者在日志里，ChatGPT相关的内容都有什么？

并不是每个报错都会发图给你的管理群，ChatGPT有些连接类的错误他只会在日志里输出一个消息，你要去看日志，不要只看群。

**Comment by MATBBB0** [comment]
我看日志里好像跟我截出来的是差不多的。那我先去整一下最近的大创，等下个版本用文心一言再试试。谢谢大佬帮我解答这么多

**Comment by hsyhhssyy** [comment]
新的4.0.0插件已经上架了，可以配合官方插件里的大语言模型库，来使用文心一言，快去试一下吧。

**Comment by MATBBB0** [comment]
> 新的4.0.0插件已经上架了，可以配合官方插件里的大语言模型库，来使用文心一言，快去试一下吧。

好滴，最近在忙期末考，考完了之后试一下，谢谢大佬TOT
