### ISSUE TITLE
回复时未按照预定义上下文回复

### ISSUE THREAD

**Issue by desktop4025** [hsyhhssyy/amiyabot-hsyhhssyy-chatgpt#18]
我使用的是新加的百度大语言模型，兔兔未安装常规设置里的背景进行回复。
![图片](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/assets/107090995/289c32ef-bb0f-44c2-afa2-f4d9b26c4d4f)
![图片](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/assets/107090995/317c2bf9-cfce-491f-9c6e-2934a4adffb5)
![图片](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/assets/107090995/f2b6284e-758e-4a71-9eb4-65b0fea01e97)

**Comment by hsyhhssyy** [comment]
你能打开详细日志（包括大语言模型库的和ChatGPT插件的）然后把日志发过来我看一下吗？我看看你的原始请求是什么。

我看一下是文心一言太蠢还是预定义的设定没应用上。

**Comment by desktop4025** [comment]
我好像没有找到插件里面具体的log，只找到了server的log，不知道是不是这个
![图片](https://github.com/hsyhhssyy/amiyabot-hsyhhssyy-chatgpt/assets/107090995/1753b62d-45bc-4280-9e7c-59b024cce978)

**Comment by desktop4025** [comment]
> 你能打开详细日志（包括大语言模型库的和ChatGPT插件的）然后把日志发过来我看一下吗？我看看你的原始请求是什么。
> 
> 我看一下是文心一言太蠢还是预定义的设定没应用上。

大佬有什么qq群可以联系到你吗，好像兔妈的频道你不在？

**Comment by hsyhhssyy** [comment]
我的QQ号不能加频道
没事，我先看一下，我觉得可能是我插件的问题。

**Comment by desktop4025** [comment]
好的嘞

**Comment by hsyhhssyy** [comment]
查出来了，确实有bug，我提交了一个新版本4.1.1，你试试

**Comment by desktop4025** [comment]
修好啦，谢谢大佬
