### ISSUE TITLE
可以加一个proxy配置项吗

### ISSUE THREAD

**Issue by wutongshufqw** [hsyhhssyy/amiyabot-hsyhhssyy-chatgpt#4]

**Comment by hsyhhssyy** [comment]
这个得你电脑自己配置全局proxy，因为openai的api库没有proxy参数。
linux的话，你得用tproxy

**Comment by wutongshufqw** [comment]
是有的我看过了
我自己改了先用上了

**Comment by wutongshufqw** [comment]
![image](https://user-images.githubusercontent.com/87960738/224323513-cc499502-3643-4247-8a89-fd63a0dacc75.png)
![image](https://user-images.githubusercontent.com/87960738/224323659-4a6eed3a-4146-449e-9c79-d648fa116627.png)

**Comment by hsyhhssyy** [comment]
我自己的兔兔跑在docker里，有全局proxy，所以没什么大问题，我也推荐这样，方便更新lib啥的
插件没办法改openai的lib，除非自己做request，但是那太麻烦了。

**Comment by wutongshufqw** [comment]
也就是说像我那样写没有用吗

**Comment by hsyhhssyy** [comment]
> 
我刚刚仔细的读了一下，好像是可以的，我加上吧，不过我用不上，你可以测试一下反馈一下。

**Comment by wutongshufqw** [comment]
好的

**Comment by hsyhhssyy** [comment]
我发布了一个2.1，你试一下看看

**Comment by wutongshufqw** [comment]
![image](https://user-images.githubusercontent.com/87960738/224343688-c7f5f852-f93e-4b03-8636-d05a07f9682c.png)
类似这样子

**Comment by wutongshufqw** [comment]
对，像我上面那样写就可以解决了，我测试改过了

**Comment by wutongshufqw** [comment]
对，像我上面那样写就可以解决了，我测试改过了

**Comment by wutongshufqw** [comment]
![image](https://user-images.githubusercontent.com/87960738/224346229-656a4118-1f3d-4df9-bd2a-5b6b3fa7dfe3.png)
像这样写就好了

**Comment by hsyhhssyy** [comment]
很久以前的版本里我是加了异步的，但是后面又取消掉了
好像当年openapi的api在并发的时候会有一些问题，不知道现在修复了没有。

所以理论上最好的实现方式是加上异步但是要保证chatgpt调用是顺序执行的。
这个写起来太麻烦了所以我还没弄。

此外兔妈提供了一个run_in_thread_pool函数，那个会更好一些

**Comment by hsyhhssyy** [comment]
新版已经处理好了异步，这个case关闭了。
