### ISSUE TITLE
能否对阿米娅的身份配置进行改进？

### ISSUE THREAD

**Issue by niucattle** [hsyhhssyy/amiyabot-hsyhhssyy-chatgpt#5]
现在阿米娅还是会经常性的说自己是AI助手，而问什么问题她都会回答自己是罗德岛的领袖，不关心自己，巴拉巴拉，太严肃了
![E`BEMYD4{D_{(YF{~D61EUY](https://user-images.githubusercontent.com/118875129/224231892-7d38a2f9-ce9c-4ee2-a113-432f0aca84f5.png)

**Comment by niucattle** [comment]
> AI助手那个，我下个版本会改。 但是回答这个，感觉微软调整了ai，最近他变蠢了，我下个版本会加入自定义前置上下文的配置项，到时候你可以自己调。
![image](https://user-images.githubusercontent.com/118875129/224457180-67e68e0f-81fa-464b-83e4-1a13b61527de.png)

**Comment by niucattle** [comment]
![image](https://user-images.githubusercontent.com/118875129/224457209-33dffe85-3f87-4a86-b285-7fdfd114094c.png)
好像妹变啊

**Comment by hsyhhssyy** [comment]
你要去配置文件里自己调
你看一下插件的说明

**Comment by hsyhhssyy** [comment]
你改的是插件带的末认配置文件，还是resource目录下的那个？

**Comment by hsyhhssyy** [comment]
此外根据官方文档，GPT-3不一定会严格依赖system提示。

**Comment by niucattle** [comment]
> 

额，我没删除resource下的config，当时看到resource里的没相关配置，插件目录下有，就去改插件目录的config了

**Comment by hsyhhssyy** [comment]
> 额，我没删除resource下的config，当时看到resource里的没相关配置，插件目录下有，就去改插件目录的config了

插件目录下面那个只是个模版，如果resources下面没有文件会把模版复制过去，仅此而已。
