### ISSUE TITLE
佬有兴趣像yunzai一样整个反向代理模式吗

### ISSUE THREAD

**Issue by niucattle** [hsyhhssyy/amiyabot-hsyhhssyy-chatgpt#6]
![-704c3a2b88118d7c](https://user-images.githubusercontent.com/118875129/224678901-ef641ecb-aded-45f2-8738-7cc25032cf32.jpg)

**Comment by niucattle** [comment]
这样不用挂代理也能调用api了

**Comment by hsyhhssyy** [comment]
这个没有兴趣

**Comment by hsyhhssyy** [comment]
新版的插件加了一个新配置项”base_url“，可以支持反代了，不过因为里面用了兔兔还未发布的新特性，所以要等兔兔版本先更新。

**Comment by hsyhhssyy** [comment]
所以我把这个issue重新打开了，到时候发布了你可以测试一下

**Comment by niucattle** [comment]
好滴

**Comment by niucattle** [comment]
emm 估计我是没法测试了 域名之前被我玩的被GFW认证了

**Comment by hsyhhssyy** [comment]
没事，我自己测过了，是ok的，而且这个版本也已经上架了应该
